version: '3'
services:
  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=r00tP4ssw0rd
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    networks:
      - petclinic

  frontend:
    restart: always
    container_name: frontend
    image: frontend:latest
    build: 
      context: .
      dockerfile: frontend/docker/Dockerfile
    # command: sh -c "serve -s build -l 80 --no-clipboard"
    command: sh -c "npm start"
    ports:
      - 80:3000
    networks:
      - petclinic

  backend:
    restart: always
    container_name: backend
    image: backend:latest
    build: 
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
    environment:
        spring.datasource.url: jdbc:mysql://mysql:3306/petclinic?allowPublicKeyRetrieval=true
    depends_on:
      - mysql
    networks:
      - petclinic
    volumes:
      - .m2:/root/.m2

networks:
  petclinic:
    driver: bridge
